#!/usr/bin/env python3
"""Regenerate src/frameworks/table.rs — the ATT&CK and MBC id → name table.

Sources are the official STIX bundles:

  https://github.com/mitre-attack/attack-stix-data   (enterprise, mobile, ics)
  https://github.com/MBCProject/mbc-stix2.1          (mbc/mbc.json)

Usage:
  scripts/gen-framework-names.py                 # download and regenerate
  scripts/gen-framework-names.py DIR             # use bundles already in DIR

The table carries every technique, sub-technique, behavior, and method id,
revoked and deprecated ones included: a trait may still cite them, and a
stale name beats a bare id.
"""

import json
import sys
import urllib.request
from pathlib import Path

ATTACK = "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/{d}/{d}.json"
MBC = "https://raw.githubusercontent.com/MBCProject/mbc-stix2.1/main/mbc/mbc.json"
DOMAINS = ("enterprise-attack", "mobile-attack", "ics-attack")
OUT = Path(__file__).resolve().parent.parent / "src" / "frameworks" / "table.rs"


def load(cache: Path | None, name: str, url: str) -> dict:
    if cache is not None:
        return json.loads((cache / name).read_text())
    with urllib.request.urlopen(url, timeout=120) as r:
        return json.load(r)


def attack_names(bundle: dict) -> dict[str, str]:
    names = {}
    for o in bundle["objects"]:
        if o.get("type") != "attack-pattern":
            continue
        for r in o.get("external_references", []):
            eid = r.get("external_id", "")
            if r.get("source_name") == "mitre-attack" and eid.startswith("T"):
                names.setdefault(eid, o["name"])
    return names


def mbc_names(bundle: dict) -> dict[str, str]:
    names = {}
    for o in bundle["objects"]:
        d = o.get("obj_defn") or {}
        eid = d.get("external_id", "")
        if d.get("source_name") == "mitre-mbc" and eid[:1] in "BCE":
            names.setdefault(eid, o["name"])
    return names


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    cache = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    attack: dict[str, str] = {}
    for d in DOMAINS:
        attack.update({k: v for k, v in attack_names(load(cache, f"{d}.json", ATTACK.format(d=d))).items() if k not in attack})
    mbc = mbc_names(load(cache, "mbc.json", MBC))
    lines = [
        "//! Generated by scripts/gen-framework-names.py — do not edit.",
        "//!",
        "//! Sorted by id, so [`super::name`] can binary-search.",
        "",
        "#[rustfmt::skip]",
        "pub(super) const ATTACK: &[(&str, &str)] = &[",
        *(f"    ({rust_str(k)}, {rust_str(v)})," for k, v in sorted(attack.items())),
        "];",
        "",
        "#[rustfmt::skip]",
        "pub(super) const MBC: &[(&str, &str)] = &[",
        *(f"    ({rust_str(k)}, {rust_str(v)})," for k, v in sorted(mbc.items())),
        "];",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(attack)} ATT&CK ids, {len(mbc)} MBC ids")


if __name__ == "__main__":
    main()
